package com.adedom.teg.db

object DatabaseConstant {

    const val playerTable = "player"
    const val itemCollectionTable = "item_collection"
    const val logActiveTable = "log_active"
    const val multiTable = "multi"
    const val multiCollectionTable = "multi_collection"
    const val roomTable = "room"
    const val roomInfoTable = "room_info"

    const val playerPk = "PK_Player_ID"
    const val itemCollectionPk = "PK_ItemCollection_ID"
    const val logActivePk = "PK_LogActive_ID"
    const val multiPk = "PK_Multi_ID"
    const val multiCollectionPk = "PK_MultiCollection_ID"
    const val roomPk = "PK_Room_ID"
    const val roomInfoPk = "PK_RoomInfo_ID"

    const val playerId = "player_id"
    const val username = "username"
    const val name = "name"
    const val image = "image"
    const val state = "state"
    const val gender = "gender"
    const val dateTime = "date_time"
    const val collectionId = "collection_id"
    const val itemId = "item_id"
    const val qty = "qty"
    const val latitude = "latitude"
    const val longitude = "longitude"
    const val logId = "log_id"
    const val logKey = "log_key"
    const val dateTimeIn = "date_time_in"
    const val dateTimeOut = "date_time_out"
    const val multiId = "multi_id"
    const val roomNo = "room_no"
    const val status = "status"
    const val score = "score"
    const val team = "team"
    const val roomId = "room_id"
    const val people = "people"
    const val infoId = "info_id"

}
